import path from 'path';

export const Constants = {
  ENV_VARS_KEY: 'sirjiSecrets',
  CODER_JSON_FILE: 'coder.json',
  PLANNER_JSON_FILE: 'planner.json',
  RESEARCHER_JSON_FILE: 'researcher.json',
  PYTHON_INPUT_FILE: 'input.txt',
  PROMPT_TOKEN_PRICE_PER_MILLION_TOKENS: 10,
  COMPLETION_TOKEN_PRICE_PER_MILLION_TOKENS: 30,
  SESSIONS: 'sessions'
};

export const ACTION_ENUM = {
  //user and coder conversations
  PROBLEM_STATEMENT: 'PROBLEM_STATEMENT',
  QUESTION: 'QUESTION',
  ANSWER: 'ANSWER',
  INFORM: 'INFORM',
  SOLUTION_COMPLETE: 'SOLUTION_COMPLETE',
  FEEDBACK: 'FEEDBACK',

  // coder and planner conversations
  GENERATE_STEPS: 'GENERATE_STEPS',
  STEPS: 'STEPS',

  //coder and researcher conversations
  TRAIN_USING_URL: 'TRAIN_USING_URL',
  TRAIN_USING_SEARCH_TERM: 'TRAIN_USING_SEARCH_TERM',
  TRAINING_OUTPUT: 'TRAINING_OUTPUT',
  INFER: 'INFER',
  RESPONSE: 'RESPONSE',

  //coder and executor conversations
  EXECUTE_COMMAND: 'EXECUTE_COMMAND',
  RUN_SERVER: 'RUN_SERVER',
  CREATE_WORKSPACE_FILE: 'CREATE_WORKSPACE_FILE',
  READ_WORKSPACE_FILES: 'READ_WORKSPACE_FILES',
  READ_DIR_STRUCTURE: 'READ_DIR_STRUCTURE',
  OUTPUT: 'OUTPUT',
  OPEN_BROWSER: 'OPEN_BROWSER',
  CREATE_SHARED_RESOURCE_FILE: 'CREATE_SHARED_RESOURCE_FILE',
  READ_SHARED_RESOURCES_FILES: 'READ_SHARED_RESOURCES_FILES',
  APPEND_TO_SHARED_RESOURCES_INDEX: 'APPEND_TO_SHARED_RESOURCES_INDEX',
  READ_SHARED_RESOURCE_INDEX: 'READ_SHARED_RESOURCE_INDEX',
  SEARCH_FILE_IN_WORKSPACE: 'SEARCH_FILE_IN_WORKSPACE',
  FIND_AND_REPLACE: 'FIND_AND_REPLACE',
  INSERT_TEXT: 'INSERT_TEXT',
  EXTRACT_DEPENDENCIES: 'EXTRACT_DEPENDENCIES'
};

export const ACTOR_ENUM = {
  USER: 'SIRJI_USER',
  CODER: 'CODER',
  PLANNER: 'PLANNER',
  RESEARCHER: 'RESEARCHER',
  EXECUTOR: 'EXECUTOR',
  ORCHESTRATOR: 'ORCHESTRATOR',
  SHORTLISTER: 'SHORTLISTER'
};
