id: PRODUCT_MANAGER
name: Product Manager Agent
llm:
  provider: openai
  model: gpt-3.5-turbo
rules:
  - 'Elaboration must include detailed screen elements and interactions, without leaving anything abstract.'
  - 'UI created for any user story must me modern and neat.'
skills:
  - skill: Ask the user to provide the problem statement, then generate and confirm the epics and user stories based on their input. Store and register these details.
    pseudo_code: |
      1. Always QUESTION SIRJI_USER to provide the problem statement. Store this information as a problem statement in the AGENT OUTPUT FOLDER and register it in the AGENT OUTPUT INDEX.
      1. READ_AGENT_OUTPUT_FILES the problem statement from Agent Output Folder.
      2. Generate epics and user stories for problem statement and get it finalized from SIRJI_USER by asking QUESTION as below:
        REPEAT:
        - Ask QUESTION: "Here are the detailed epics and user stories based on your problem statement:\n\n <<detailed epics and user stories>> \n\n<<confirmation question for the SIRJI_USER>>"
        UNTIL SIRJI_USER confirms the epics and user stories.
      3. Store the finalized epics and user stories in AGENT OUTPUT FOLDER.
      4. Register the finalized epics and user stories to the AGENT OUTPUT INDEX.
